import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html, type TemplateResult } from 'lit';

import {
  colorTokens,
  darkColorTokens,
  motionTokens,
  radiusTokens,
  shadowTokens,
  spaceTokens,
  typographyTokens,
  zTokens,
} from 'pillkit-tokens';

/**
 * Token reference (spec 5.5) — the canonical listing with light/dark values
 * side by side.
 *
 * RECORDED CHOICE — generation path: the page imports the GENERATED typed
 * token maps from pillkit-tokens (src/tokens.ts, regenerated by
 * `pnpm gen:tokens` from DESIGN.md and drift-gated by check:tokens-drift).
 * Drift is impossible BY CONSTRUCTION: the tables render the same objects
 * the components consume — a token-layer change flows into this page with
 * the next build, and the visual harness re-baselines it. No values are
 * hand-typed anywhere below; the only literals are STRUCTURE (family
 * grouping rules, table chrome), never values.
 *
 * Dark columns: the dark layer re-declares SEMANTIC color tokens only
 * (darkColorTokens). A token absent there is theme-invariant — shown as
 * «инвариантно», never as a duplicated value.
 *
 * Content RU (OQ-4), story meta EN for baseline stability.
 */

type TokenMap = Record<string, string>;

const meta: Meta = {
  title: 'Token Reference',
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;

type Story = StoryObj;

const pageStyles = html`
  <style>
    .tktr {
      box-sizing: border-box;
      max-width: var(--tk-space-container);
      margin: 0 auto;
      padding: var(--tk-space-40) var(--tk-space-24) var(--tk-space-96);
      font-family: var(--tk-font-body);
      font-size: var(--tk-text-body-m-size);
      font-weight: var(--tk-text-body-m-weight);
      line-height: var(--tk-text-body-m-leading);
      color: var(--tk-color-text-primary);
      /* Canvas follows the theme's base surface (the 5.4 dark-sweep rule). */
      background: var(--tk-color-surface-base);
    }
    .tktr h1 {
      margin: 0 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-3-size);
      font-weight: var(--tk-text-heading-3-weight);
      line-height: var(--tk-text-heading-3-leading);
    }
    .tktr h2 {
      margin: var(--tk-space-40) 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-5-size);
      font-weight: var(--tk-text-heading-5-weight);
      line-height: var(--tk-text-heading-5-leading);
    }
    .tktr h3 {
      margin: var(--tk-space-24) 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-6-size);
      font-weight: var(--tk-text-heading-6-weight);
      line-height: var(--tk-text-heading-6-leading);
    }
    .tktr p {
      margin: 0 0 var(--tk-space-12);
      max-width: var(--tk-space-container);
    }
    .tktr .tktr-note {
      color: var(--tk-color-text-secondary);
    }
    .tktr table {
      box-sizing: border-box;
      width: 100%;
      margin: 0 0 var(--tk-space-16);
      border-collapse: collapse;
      font-size: var(--tk-text-body-s-size);
      line-height: var(--tk-text-body-s-leading);
      text-align: left;
    }
    .tktr th,
    .tktr td {
      padding: var(--tk-space-8) var(--tk-space-12) var(--tk-space-8) 0;
      border-bottom: 1px solid var(--tk-color-border-default);
      vertical-align: middle;
    }
    .tktr th {
      font-size: var(--tk-text-body-xs-size);
      font-weight: var(--tk-text-body-s-bold-weight);
      letter-spacing: var(--tk-text-caps-s-tracking);
      text-transform: uppercase;
      color: var(--tk-color-text-secondary);
    }
    .tktr code {
      font-family: var(--tk-font-body);
      white-space: nowrap;
    }
    .tktr .tktr-swatch {
      box-sizing: border-box;
      display: inline-block;
      vertical-align: middle;
      width: var(--tk-space-40);
      height: var(--tk-space-24);
      margin-right: var(--tk-space-12);
      border: 1px solid var(--tk-color-border-strong);
      border-radius: var(--tk-radius-xs);
    }
    /* AA note: real content never rides on text-muted (the restricted token);
       «инвариантно» is content — it takes the secondary step. */
    .tktr .tktr-invariant {
      color: var(--tk-color-text-secondary);
    }
    .tktr .tktr-radius-box {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-64);
      height: var(--tk-space-64);
      border: 2px solid var(--tk-color-focus-ring);
    }
    .tktr .tktr-space-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-text-body-s-size);
      background: var(--tk-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tktr .tktr-shadow-box {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-120);
      height: var(--tk-space-64);
      background: var(--tk-color-surface-base);
      border-radius: var(--tk-radius-sm);
    }
    .tktr .tktr-duration-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-text-body-s-size);
      background: var(--tk-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tktr .tktr-curve {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-96);
      height: var(--tk-space-96);
    }
    .tktr .tktr-z-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-space-12);
      background: var(--tk-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tktr .tktr-specimen {
      margin: 0;
      overflow-wrap: anywhere;
    }
  </style>
`;

/* --- Derivation helpers: STRUCTURE only — every VALUE comes from the maps --- */

/** Value cells for a token: the light value and its dark counterpart. */
function darkValueOf(name: string): string | null {
  return Object.prototype.hasOwnProperty.call(darkColorTokens, name)
    ? darkColorTokens[name as keyof typeof darkColorTokens]
    : null;
}

/**
 * Swatch fill for a value that may carry alpha (the dark layer's #FFFFFF1A
 * family): the value is layered OVER an invariant gray-200 chip so
 * translucency stays visible on the light page. Opaque values cover the
 * backing completely.
 */
function swatchFill(value: string): string {
  return `background-image: linear-gradient(${value}, ${value}); background-color: var(--tk-color-gray-200)`;
}

/** One table row for a color token: swatches + light/dark values side by side. */
function colorRow([name, light]: [string, string]): TemplateResult {
  const dark = darkValueOf(name);
  return html`
    <tr>
      <td><code>${name}</code></td>
      <td>
        <span class="tktr-swatch" style="${swatchFill(light)}"></span
        ><code>${light}</code>
      </td>
      <td>
        ${dark
          ? html`<span class="tktr-swatch" style="${swatchFill(dark)}"></span
              ><code>${dark}</code>`
          : html`<span class="tktr-invariant">инвариантно</span>`}
      </td>
    </tr>
  `;
}

/** Split the color map into families by NAME SHAPE (never by value). */
function splitColorFamilies(tokens: TokenMap): {
  scales: [string, string][];
  semantic: [string, string][];
  tints: [string, string][];
} {
  const scales: [string, string][] = [];
  const semantic: [string, string][] = [];
  const tints: [string, string][] = [];
  for (const entry of Object.entries(tokens)) {
    if (/^--tk-color-tint-/.test(entry[0])) tints.push(entry);
    else if (/^--tk-color-[a-z]+-\d+$/.test(entry[0]) || entry[0] === '--tk-color-white')
      scales.push(entry);
    else semantic.push(entry);
  }
  return { scales, semantic, tints };
}

const colorsTable = (rows: [string, string][]): TemplateResult => html`
  <table>
    <thead>
      <tr>
        <th>Токен</th>
        <th>Светлая тема</th>
        <th>Тёмная тема</th>
      </tr>
    </thead>
    <tbody>
      ${rows.map(colorRow)}
    </tbody>
  </table>
`;

/* --- Motion: sample a css cubic-bezier into SVG polyline points --- */

/** Uniformly-x-sampled points of a cubic-bezier(…) string (structure, no values). */
function bezierSamples(spec: string): Array<[number, number]> {
  const m = /cubic-bezier\(([-\d.]+),([-\d.]+),([-\d.]+),([-\d.]+)\)/.exec(spec);
  if (!m) return [];
  const [x1, y1, x2, y2] = m.slice(1).map(Number);
  const bx = (t: number): number => 3 * (1 - t) ** 2 * t * x1 + 3 * (1 - t) * t ** 2 * x2 + t ** 3;
  const by = (t: number): number => 3 * (1 - t) ** 2 * t * y1 + 3 * (1 - t) * t ** 2 * y2 + t ** 3;
  const points: Array<[number, number]> = [];
  for (let i = 0; i <= 20; i += 1) {
    const x = i / 20;
    // x(t) is monotonic for these curves — bisect for the param at x.
    let lo = 0;
    let hi = 1;
    for (let k = 0; k < 32; k += 1) {
      const mid = (lo + hi) / 2;
      if (bx(mid) < x) lo = mid;
      else hi = mid;
    }
    const t = (lo + hi) / 2;
    points.push([x, by(t)]);
  }
  return points;
}

/** Static SVG preview of a curve token — no animation (baseline-deterministic). */
function curveSvg(spec: string): TemplateResult {
  // Overshoot curves (y outside 0..1) fit the padded box: [-0.3, 1.3] → 5..125.
  const px = (p: [number, number]): string =>
    `${(p[0] * 100).toFixed(1)},${(125 - ((p[1] + 0.3) / 1.6) * 120).toFixed(1)}`;
  const points = bezierSamples(spec).map(px).join(' ');
  return html`
    <svg
      class="tktr-curve"
      viewBox="0 0 100 130"
      preserveAspectRatio="none"
      aria-hidden="true"
      focusable="false"
    >
      <line x1="0" y1="102.5" x2="100" y2="102.5" style="stroke: var(--tk-color-border-default)" />
      <line x1="0" y1="27.5" x2="100" y2="27.5" style="stroke: var(--tk-color-border-default)" />
      <polyline
        points="${points}"
        fill="none"
        style="stroke: var(--tk-color-focus-ring); stroke-width: 3"
      />
    </svg>
  `;
}

/* --- Stories ------------------------------------------------------------------ */

export const Colors: Story = {
  name: 'Цвета',
  render: () => {
    const { scales, semantic, tints } = splitColorFamilies(colorTokens as TokenMap);
    return html`
      ${pageStyles}
      <main class="tktr">
        <h1>Токены — цвета</h1>
        <p class="tktr-note">
          Значения сгенерированы из дизайн-модели (<code>pnpm gen:tokens</code>,
          источник — DESIGN.md) и приведены ровно в том виде, в котором их
          потребляют компоненты. Тёмная колонка — семантические переопределения
          слоя <code>data-theme="dark"</code>; «инвариантно» значит, что тёмный
          слой токен не переопределяет.
        </p>

        <h2>Семантические токены</h2>
        <p class="tktr-note">
          Поверхности, границы, текст, ссылки, ошибки и кольцо фокуса. Компоненты
          потребляют только семантику — переопределяйте при необходимости именно
          эти токены, а не шкалы.
        </p>
        ${colorsTable(semantic)}

        <h2>Оттенки карточек</h2>
        <p class="tktr-note">
          Пастельные подложки карточных вариантов. Charcoal инвариантен: тёмная
          тема его не меняет, текст на нём остаётся белым в обеих темах.
        </p>
        ${colorsTable(tints)}

        <h2>Шкалы</h2>
        <p class="tktr-note">
          Сырые извлечённые шкалы. Тёмный слой их не переопределяет: семантика
          ссылается на шкалы, а темы меняют семантику.
        </p>
        ${colorsTable(scales)}
      </main>
    `;
  },
};

export const Typography: Story = {
  name: 'Типографика',
  render: () => {
    // Group per-slot tokens (…-size/-weight/-leading/-tracking) by stem, in
    // emission order — names only, values stay in the map.
    const slots: Array<{ stem: string; parts: Record<string, string> }> = [];
    for (const [name, value] of Object.entries(typographyTokens as TokenMap)) {
      if (!name.startsWith('--tk-text-')) continue;
      const rest = name.replace('--tk-text-', '');
      const part = rest.match(/-(size|weight|leading|tracking)$/)?.[1];
      if (!part) continue;
      const stem = rest.slice(0, rest.length - part.length - 1);
      const slot = slots.find((s) => s.stem === stem) ?? (slots.push({ stem, parts: {} }), slots.at(-1)!);
      slot.parts[part] = value;
    }
    const fonts = Object.entries(typographyTokens as TokenMap).filter(([n]) =>
      n.startsWith('--tk-font-'),
    );
    return html`
      ${pageStyles}
      <main class="tktr">
        <h1>Токены — типографика</h1>
        <p class="tktr-note">
          Типографика инвариантна по темам: один набор на обе. Каждая строка —
          слот с его размером, насыщенностью и межстрочным; образец справа
          рендерится живыми токенами. Семейства — в двух слотах ниже.
        </p>

        <h2>Слоты текста</h2>
        <table>
          <thead>
            <tr>
              <th>Слот</th>
              <th>Размер</th>
              <th>Насыщенность</th>
              <th>Межстрочный</th>
              <th>Трекинг</th>
              <th>Образец</th>
            </tr>
          </thead>
          <tbody>
            ${slots.map(
              ({ stem, parts }) => html`
                <tr>
                  <td><code>${stem}</code></td>
                  <td><code>${parts.size ?? '—'}</code></td>
                  <td><code>${parts.weight ?? '—'}</code></td>
                  <td><code>${parts.leading ?? '—'}</code></td>
                  <td><code>${parts.tracking ?? '—'}</code></td>
                  <td
                    style="font-family: var(--tk-font-${stem.startsWith('heading-') ? 'heading' : 'body'}); font-size: var(--tk-text-${stem}-size); font-weight: var(--tk-text-${stem}-weight); line-height: var(--tk-text-${stem}-leading); ${parts.tracking
                      ? `letter-spacing: var(--tk-text-${stem}-tracking);`
                      : ''}"
                  >
                    <p class="tktr-specimen">СмартВклад 1 331 ₽</p>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Слоты семейств</h2>
        <p class="tktr-note">
          Стек начинается с бренд-шрифтов и несёт открытый fallback: если
          собственных шрифтов нет, рендерится Inter. Переопределение слота
          заменяет значение целиком — повторите fallback в конце.
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Стек</th><th>Тёмная тема</th></tr>
          </thead>
          <tbody>
            ${fonts.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td><span class="tktr-invariant">инвариантно</span></td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </main>
    `;
  },
};

export const Surfaces: Story = {
  name: 'Форма и поверхность',
  render: () => {
    const radii = Object.entries(radiusTokens as TokenMap);
    const spaces = Object.entries(spaceTokens as TokenMap).filter(
      ([n]) => !n.endsWith('-container') && !n.endsWith('-grid-gap'),
    );
    const layout = Object.entries(spaceTokens as TokenMap).filter(
      ([n]) => n.endsWith('-container') || n.endsWith('-grid-gap'),
    );
    const shadows = Object.entries(shadowTokens as TokenMap);
    // Derived from the maps — bars can never overflow if the scale grows.
    const spaceScaleMax = Math.max(
      ...spaces.map(([, v]) => parseFloat(v) || 0),
      1,
    );
    return html`
      ${pageStyles}
      <main class="tktr">
        <h1>Токены — форма и поверхность</h1>
        <p class="tktr-note">
          Радиусы, отступы и тени инвариантны по темам. Единственное
        исключение — тени: в тёмной теме слой схлопывает их в
        <code>none</code>, иерархию строят тональные ступени поверхностей.
        </p>

        <h2>Радиусы</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Образец</th></tr>
          </thead>
          <tbody>
            ${radii.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tktr-radius-box"
                      style="border-radius: var(${name})"
                    ></span>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Отступы</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Шкала</th></tr>
          </thead>
          <tbody>
            ${spaces.map(([name, value]) => {
              const px = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tktr-space-bar"
                      style="width: ${(100 * px) / spaceScaleMax}%"
                    ></span>
                  </td>
                </tr>
              `;
            })}
            ${layout.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td><span class="tktr-invariant">макетная константа</span></td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Тени</h2>
        <p class="tktr-note">
          Образцы ниже рендерятся живыми токенами: переключите контрол Theme —
          в тёмной теме они исчезнут вместе со значением токена.
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Образец</th></tr>
          </thead>
          <tbody>
            ${shadows.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span class="tktr-shadow-box" style="box-shadow: var(${name})"></span>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </main>
    `;
  },
};

export const Motion: Story = {
  name: 'Моушен и z-шкала',
  render: () => {
    const curves = Object.entries(motionTokens as TokenMap).filter(([n]) =>
      n.includes('-curve-'),
    );
    const durations = Object.entries(motionTokens as TokenMap).filter(([n]) =>
      n.includes('-duration-'),
    );
    // Derived from the maps — bars can never overflow if the scale grows.
    const durationMax = Math.max(
      ...durations.map(([, v]) => parseFloat(v) || 0),
      1,
    );
    const zs = Object.entries(zTokens as TokenMap);
    const zMax = Math.max(...zs.map(([, v]) => parseFloat(v) || 0), 1);
    return html`
      ${pageStyles}
      <main class="tktr">
        <h1>Токены — моушен и z-шкала</h1>
        <p class="tktr-note">
          Кривые и длительности — единственный источник движения кита (AD-9);
          под <code>prefers-reduced-motion</code> длительности схлопываются в
          0ms самим токеновым слоем. z-шкала — порядок оверлеев (AD-12).
          Инвариантны по темам.
        </p>

        <h2>Кривые</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Профиль</th></tr>
          </thead>
          <tbody>
            ${curves.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>${curveSvg(value)}</td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Длительности</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Шкала</th></tr>
          </thead>
          <tbody>
            ${durations.map(([name, value]) => {
              const ms = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tktr-duration-bar"
                      style="width: ${(100 * ms) / durationMax}%"
                    ></span>
                  </td>
                </tr>
              `;
            })}
          </tbody>
        </table>

        <h2>Z-шкала</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Уровень</th></tr>
          </thead>
          <tbody>
            ${zs.map(([name, value]) => {
              const level = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span class="tktr-z-bar" style="width: ${(100 * level) / zMax}%"></span>
                  </td>
                </tr>
              `;
            })}
          </tbody>
        </table>
      </main>
    `;
  },
};
