/**
 * @tk-kit/tokens — design token package for tinkoff-ui-kit.
 *
 * Programmatic access to the token system: typed name/value maps generated from
 * DESIGN.md (`./tokens.js`). Styles ship as the `@tk-kit/tokens/tokens.css`
 * export: the side-effect import below pulls the light `--tk-*` layer through
 * bundlers that consume this source, while the built library extracts the CSS
 * to dist/index.css and strips the import from dist JS — stylesheet consumers
 * always use the export.
 *
 * Generated by `pnpm gen:tokens` (scripts/generate.mjs); DESIGN.md is the sole
 * source of truth — never hand-edit `tokens.css`, `tokens.ts`, or `TOKENS.md`.
 * The dark layer on `[data-theme="dark"]` lands in Story 1.3.
 */
import './tokens.css';

export * from './tokens.js';
