import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * Gen-pipeline drift guard (spec 1.7 review, tokens-drift style): `check:gen`
 * is manual-only — a component edit that forgets `pnpm gen` used to land with
 * every gate green. This suite RUNS the real generators (`cem analyze` with
 * the committed config in packages/components, then the react wrapper
 * generator), asserts the regenerated bytes equal the committed ones, and
 * RESTORES the originals on the way out — so `pnpm test` fails on drift
 * without the write step mutating the tree.
 */

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const COMPONENTS_DIR = join(REPO_ROOT, 'packages', 'components');
const GENERATED_DIR = join(REPO_ROOT, 'packages', 'react', 'src', 'generated');
const MANIFEST = join(COMPONENTS_DIR, 'custom-elements.json');

/** The drift-gated artifacts: the committed manifest + every generated wrapper. */
function readArtifactState(): Map<string, string> {
  const state = new Map<string, string>([[MANIFEST, readFileSync(MANIFEST, 'utf8')]]);
  for (const entry of readdirSync(GENERATED_DIR).sort()) {
    if (entry.endsWith('.ts') || entry.endsWith('.tsx')) {
      const path = join(GENERATED_DIR, entry);
      state.set(path, readFileSync(path, 'utf8'));
    }
  }
  return state;
}

describe('gen-pipeline drift (spec 1.7 review)', () => {
  it('committed manifest + wrappers equal a fresh generation', () => {
    const committed = readArtifactState();
    expect(committed.size).toBeGreaterThan(1); // manifest + at least one wrapper

    try {
      execFileSync('cem', ['analyze', '--config', 'cem.config.mjs'], {
        cwd: COMPONENTS_DIR,
        stdio: 'pipe',
      });
      execFileSync('node', ['scripts/generate-wrappers.mjs'], {
        cwd: join(REPO_ROOT, 'packages', 'react'),
        stdio: 'pipe',
      });

      const regenerated = readArtifactState();
      const drift: string[] = [];
      for (const path of new Set([...committed.keys(), ...regenerated.keys()])) {
        if (committed.get(path) !== regenerated.get(path)) {
          drift.push(
            committed.has(path)
              ? (regenerated.has(path) ? `changed: ${path}` : `removed: ${path}`)
              : `untracked-new: ${path}`,
          );
        }
      }
      expect(
        drift,
        'committed gen artifacts drifted — run `pnpm gen` and commit the result with the component change (CI parity: pnpm check:gen).',
      ).toEqual([]);
    } finally {
      // Restore byte-for-byte; remove files the committed state did not have
      // (the generator deletes stale wrappers — a vanished artifact is drift,
      // reported by the assertion above, not something this cleanup keeps).
      for (const [path, content] of committed) writeFileSync(path, content);
      for (const entry of readdirSync(GENERATED_DIR)) {
        const path = join(GENERATED_DIR, entry);
        if ((entry.endsWith('.ts') || entry.endsWith('.tsx')) && !committed.has(path)) {
          rmSync(path);
        }
      }
    }
  });
});
