import { execFileSync } from 'node:child_process';
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

/**
 * ТЖ gen-pipeline drift guard (16.1 review round 2, the MAJOR): the bank
 * mold (tests/gen-drift.test.ts, spec 1.7 review) covered ONLY the bank
 * family — a stale ТЖ manifest or wrapper set landed with every gate green
 * (the lens caught a committed manifest still referencing
 * components.editorial-cta after the css.ts key fix; cured by a double gen,
 * caught by NO CI leg — check:gen is manual-only). Exact calc of the bank
 * mold on the ТЖ family: RUN the real generators (cem analyze with the
 * committed config in packages/tj-components, then the ТЖ wrapper
 * generator), assert the regenerated bytes equal the committed ones, and
 * RESTORE the originals on the way out — so `pnpm test` fails on ТЖ drift
 * without the write step mutating the tree. Closes the 15.2 asymmetry
 * (tj-tokens drift had a guard; tj-gen drift had none).
 */

const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const COMPONENTS_DIR = join(REPO_ROOT, 'packages', 'tj-components');
const GENERATED_DIR = join(REPO_ROOT, 'packages', 'tj-react', 'src', 'generated');
const MANIFEST = join(COMPONENTS_DIR, 'custom-elements.json');

/** The drift-gated artifacts: the committed manifest + every generated wrapper. */
function readArtifactState(): Map<string, string> {
  const state = new Map<string, string>([[MANIFEST, readFileSync(MANIFEST, 'utf8')]]);
  for (const entry of readdirSync(GENERATED_DIR).sort()) {
    if (entry.endsWith('.ts') || entry.endsWith('.tsx')) {
      const path = join(GENERATED_DIR, entry);
      state.set(path, readFileSync(path, 'utf8'));
    }
  }
  return state;
}

describe('ТЖ gen-pipeline drift (16.1 review round 2)', () => {
  it('committed ТЖ manifest + wrappers equal a fresh generation', () => {
    const committed = readArtifactState();
    expect(committed.size).toBeGreaterThan(1); // manifest + at least one wrapper

    try {
      execFileSync('cem', ['analyze', '--config', 'cem.config.mjs'], {
        cwd: COMPONENTS_DIR,
        stdio: 'pipe',
      });
      execFileSync('node', ['scripts/generate.mjs'], {
        cwd: join(REPO_ROOT, 'packages', 'tj-react'),
        stdio: 'pipe',
      });

      const regenerated = readArtifactState();
      const drift: string[] = [];
      for (const path of new Set([...committed.keys(), ...regenerated.keys()])) {
        if (committed.get(path) !== regenerated.get(path)) {
          drift.push(
            committed.has(path)
              ? (regenerated.has(path) ? `changed: ${path}` : `removed: ${path}`)
              : `untracked-new: ${path}`,
          );
        }
      }
      expect(
        drift,
        'committed ТЖ gen artifacts drifted — run `pnpm gen` and commit the result with the component change (CI parity: pnpm check:gen).',
      ).toEqual([]);
    } finally {
      // Restore byte-for-byte; remove files the committed state did not have
      // (the generator deletes stale wrappers — a vanished artifact is drift,
      // reported by the assertion above, not something this cleanup keeps).
      for (const [path, content] of committed) writeFileSync(path, content);
      for (const entry of readdirSync(GENERATED_DIR)) {
        const path = join(GENERATED_DIR, entry);
        if ((entry.endsWith('.ts') || entry.endsWith('.tsx')) && !committed.has(path)) {
          rmSync(path);
        }
      }
    }
  });
});
