import { html, type TemplateResult } from 'lit';

import cem from '../custom-elements.json';

/**
 * Generated API reference for component stories (spec 5.5).
 *
 * RECORDED CHOICE — API-table mechanism: every component page renders its
 * API table from the COMMITTED CEM MANIFEST (custom-elements.json), imported
 * here directly. The manifest is the kit's declared API surface of record
 * (AD-1), regenerated by `pnpm gen` and drift-gated by check:gen — so the
 * tables cannot disagree with the component layer: an API edit without a
 * manifest regen fails CI before the docs could lie. Autodocs/ArgsTable was
 * the alternative; it would fork the API description surface (args controls
 * vs reference) and is not baselined by the visual harness. This story-based
 * table is one mechanism for all 19 components, in both themes.
 *
 * Manifest descriptions are quoted VERBATIM (English source — the component
 * jsdoc, which also feeds the React wrapper generation); the page chrome
 * around them is Russian (OQ-4). Translating here would fork the single
 * source; the jsdoc stays authoritative.
 *
 * Styling consumes var(--tk-*) tokens only (FR-1) — this file sits inside the
 * zero-hardcoded guard's scan root.
 */

/** Minimal CEM shapes the renderer reads (schema 1.0.0 — see cem.config.mjs). */
interface CemType {
  text?: string;
}

interface CemAttribute {
  name: string;
  fieldName?: string;
  type?: CemType;
  default?: string;
  description?: string;
}

interface CemMember {
  kind?: string;
  name?: string;
  privacy?: string;
  static?: boolean;
  type?: CemType;
  description?: string;
}

interface CemEvent {
  name: string;
  type?: CemType;
  description?: string;
}

interface CemSlot {
  name?: string;
  description?: string;
}

interface CemDeclaration {
  tagName?: string;
  attributes?: CemAttribute[];
  members?: CemMember[];
  events?: CemEvent[];
  slots?: CemSlot[];
}

interface CemManifest {
  modules?: { declarations?: CemDeclaration[] }[];
}

const manifest = cem as CemManifest;

const REPO_URL = 'https://github.com/salacoste/tinkoff-ui-kit';
const CONVENTIONS_URL = `${REPO_URL}/blob/main/packages/components/CONVENTIONS.md`;

/** Find the declaration for a tag name — missing tag fails LOUDLY (spec edge-case row). */
function findDeclaration(tag: string): CemDeclaration {
  for (const module of manifest.modules ?? []) {
    const found = (module.declarations ?? []).find((d) => d.tagName === tag);
    if (found) return found;
  }
  throw new Error(
    `api-reference: tag ${tag} not found in custom-elements.json — run pnpm gen (the manifest is the API source of record).`,
  );
}

/** A short slot label: the default slot renders as «(по умолчанию)». */
const slotLabel = (name?: string): string => (name ? name : '(по умолчанию)');

const apiStyles = html`
  <style>
    .tkap {
      box-sizing: border-box;
      max-width: var(--tk-space-container);
      padding: var(--tk-space-32) var(--tk-space-24) var(--tk-space-64);
      font-family: var(--tk-font-body);
      font-size: var(--tk-text-body-m-size);
      font-weight: var(--tk-text-body-m-weight);
      line-height: var(--tk-text-body-m-leading);
      color: var(--tk-color-text-primary);
      background: var(--tk-color-surface-base);
    }
    .tkap h1 {
      margin: 0 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-3-size);
      font-weight: var(--tk-text-heading-3-weight);
      line-height: var(--tk-text-heading-3-leading);
    }
    .tkap h2 {
      margin: var(--tk-space-32) 0 var(--tk-space-12);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-6-size);
      font-weight: var(--tk-text-heading-6-weight);
      line-height: var(--tk-text-heading-6-leading);
    }
    .tkap p {
      margin: 0 0 var(--tk-space-12);
      max-width: var(--tk-space-container);
    }
    .tkap .tkap-note {
      color: var(--tk-color-text-secondary);
    }
    .tkap table {
      box-sizing: border-box;
      width: 100%;
      margin: 0 0 var(--tk-space-16);
      border-collapse: collapse;
      font-size: var(--tk-text-body-s-size);
      line-height: var(--tk-text-body-s-leading);
      text-align: left;
    }
    .tkap th,
    .tkap td {
      padding: var(--tk-space-8) var(--tk-space-12) var(--tk-space-8) 0;
      border-bottom: 1px solid var(--tk-color-border-default);
      vertical-align: top;
    }
    .tkap th {
      font-family: var(--tk-font-body);
      font-size: var(--tk-text-body-xs-size);
      font-weight: var(--tk-text-body-s-bold-weight);
      letter-spacing: var(--tk-text-caps-s-tracking);
      text-transform: uppercase;
      color: var(--tk-color-text-secondary);
    }
    .tkap code {
      font-family: var(--tk-font-body);
      color: var(--tk-color-text-primary);
    }
    .tkap td code {
      white-space: nowrap;
    }
    .tkap .tkap-foot {
      margin: var(--tk-space-32) 0 0;
      padding: var(--tk-space-12) var(--tk-space-16);
      color: var(--tk-color-text-secondary);
      background: var(--tk-color-surface-muted);
      border-left: var(--tk-space-4) solid var(--tk-color-yellow-100);
      border-radius: var(--tk-radius-xs);
      font-size: var(--tk-text-body-s-size);
      line-height: var(--tk-text-body-s-leading);
    }
    /* The footer paints surface-muted — links there take the AA-correct
       on-tint step (the kit's own link-on-tint rule, DESIGN.md Colors). */
    .tkap .tkap-foot a {
      color: var(--tk-color-link-on-tint);
    }
  </style>
`;

/**
 * The generated API page for one kit element: attributes + property-only
 * channels, events, slots — straight from the manifest — plus the
 * CONVENTIONS.md contract link every component page carries (5.5 checklist).
 */
export function apiReferenceDoc(tag: string): TemplateResult {
  const declaration = findDeclaration(tag);
  const attributes = declaration.attributes ?? [];
  const events = declaration.events ?? [];
  const slots = declaration.slots ?? [];

  // Property-only channels: public INSTANCE fields with no reflected attribute
  // (the controlled `value`, object data like Select `options`). Derived from
  // members by ABSENCE of an attribute fieldName — never a hand list. Static
  // union constants (e.g. Button's `variants`) are class API, not element
  // props — excluded.
  const attributeFields = new Set(attributes.map((a) => a.fieldName ?? a.name));
  const propertyOnly = (declaration.members ?? []).filter(
    (m) =>
      m.kind === 'field' && !m.privacy && !m.static && m.name && !attributeFields.has(m.name),
  );

  return html`
    ${apiStyles}
    <main class="tkap">
      <h1>API — ${tag}</h1>
      <p class="tkap-note">
        Таблица сгенерирована из манифеста компонентов
        (<code>custom-elements.json</code>, обновляется командой
        <code>pnpm gen</code>) — значения не могут разойтись с кодом.
        Описания процитированы из jsdoc-документации компонента на английском:
        манифест — единый источник, он же питает генерацию React-обёрток.
      </p>

      <h2>Атрибуты и свойства</h2>
      <table>
        <thead>
          <tr>
            <th>Атрибут</th>
            <th>Свойство</th>
            <th>Тип</th>
            <th>По умолчанию</th>
            <th>Описание</th>
          </tr>
        </thead>
        <tbody>
          ${attributes.map(
            (a) => html`
              <tr>
                <td><code>${a.name}</code></td>
                <td><code>${a.fieldName ?? a.name}</code></td>
                <td><code>${a.type?.text ?? '—'}</code></td>
                <td>${a.default ? html`<code>${a.default}</code>` : '—'}</td>
                <td>${a.description ?? '—'}</td>
              </tr>
            `,
          )}
          ${propertyOnly.map(
            (m) => html`
              <tr>
                <td>—</td>
                <td><code>${m.name}</code></td>
                <td><code>${m.type?.text ?? '—'}</code></td>
                <td>—</td>
                <td>
                  ${m.description ?? '—'}
                  <br />
                  <em>Только свойство: не отражается атрибутом.</em>
                </td>
              </tr>
            `,
          )}
        </tbody>
      </table>

      <h2>События</h2>
      ${events.length
        ? html`
            <table>
              <thead>
                <tr><th>Событие</th><th>Тип</th><th>Описание</th></tr>
              </thead>
              <tbody>
                ${events.map(
                  (e) => html`
                    <tr>
                      <td><code>${e.name}</code></td>
                      <td><code>${e.type?.text ?? 'CustomEvent'}</code></td>
                      <td>${e.description ?? '—'}</td>
                    </tr>
                  `,
                )}
              </tbody>
            </table>
          `
        : html`<p>Кастомных событий нет — см. описание компонента.</p>`}

      <h2>Слоты</h2>
      ${slots.length
        ? html`
            <table>
              <thead>
                <tr><th>Слот</th><th>Описание</th></tr>
              </thead>
              <tbody>
                ${slots.map(
                  (s) => html`
                    <tr>
                      <td><code>${slotLabel(s.name)}</code></td>
                      <td>${s.description ?? '—'}</td>
                    </tr>
                  `,
                )}
              </tbody>
            </table>
          `
        : html`<p>Слотов нет — контент задаётся атрибутами и свойствами.</p>`}

      <h2>Каналы темизации</h2>
      <p>
        Кастомные свойства компонента следуют грамматике
        <code>--tk-${tag.replace(/^tk-/, '')}-&lt;slot&gt;</code> и перечислены
        в jsdoc его стилевого модуля (<code>${tag.replace(/^tk-/, '')}.css.ts</code>
        в директории компонента) вместе с токенами-умолчаниями.
      </p>

      <p class="tkap-foot">
        Контракт кита — пропсы, события, controlled/uncontrolled-режимы, слоты и
        грамматика темизации — описан в
        <a href="${CONVENTIONS_URL}" target="_blank" rel="noreferrer noopener"
          >CONVENTIONS.md</a
        >
        репозитория.
      </p>
    </main>
  `;
}
