/// <reference types="vite/client" />
import type { Meta, StoryObj } from '@storybook/web-components-vite';
import { html, type TemplateResult } from 'lit';

import {
  colorTokens,
  darkColorTokens,
  motionTokens,
  radiusTokens,
  shadowTokens,
  spaceTokens,
  typographyTokens,
  zTokens,
} from 'pillkit-tj-tokens';
// The generated canonical listing, verbatim — the Registers story (17.3)
// renders its dark-layer table, theme invariants and AA rulings from THIS
// file, never from a docs-side copy (drift-guarded by
// tests/tj-docs-registers-source.test.ts).
import tokensMarkdown from 'pillkit-tj-tokens/TOKENS.md?raw';

import { tjRegistersData, TJ_REQUIRED_NOTES } from './tj-registers.js';

/**
 * ТЖ token reference (spec 17.3) — the bank 5.5 mold duplicated-and-adapted:
 * the canonical --tj-* listing with light/dark values side by side.
 *
 * RECORDED CHOICE — generation path: the page imports the GENERATED typed
 * token maps from pillkit-tj-tokens (src/tokens.ts, regenerated by
 * `pnpm gen:tokens:tj` and drift-gated by check:tokens-drift:tj). No values
 * are hand-typed below; the only literals are STRUCTURE (family grouping
 * rules, table chrome), never values.
 *
 * RECORDED ADJUSTMENT — live swatches (the 17.2 dark-sweep contract): the
 * bank mold paints swatches with the LITERAL values; on the ТЖ family that
 * is a sweep defect (a literal never flips — every unchanged fill outside
 * the purple/gold invariants is a leftover). ТЖ swatches therefore render
 * the LIVE token `var(--tj-…)`: flipping the toolbar Theme flips the
 * specimen with the sheet. The value columns stay literal TEXT (code
 * spans) — characters, not paint.
 *
 * The restricted invariants --tj-color-ink-200 / --tj-color-ink-reference-time
 * paint NO specimen at all: both keep their light value in dark (no
 * override exists), which the sweep rightly treats as a leftover — they
 * never ride surfaces (ink-200 is the light CTA-fill duty, the cta-fill
 * semantic carries the flip; ink-reference-time is unbound in dark).
 * --tj-color-chip-ink shows as ink ON its purple ground — the only surface
 * it is legal on (the 16.2/16.3 twin-pinned pair).
 *
 * Page chrome consumes bank --tk-* (docs-site chrome is shared — the
 * standing ruling); every specimen inside consumes --tj-* only.
 *
 * Content RU (OQ-4), story meta EN for baseline stability.
 */

type TokenMap = Record<string, string>;

const meta: Meta = {
  title: 'TJ/Token Reference',
  parameters: {
    layout: 'fullscreen',
  },
};

export default meta;

type Story = StoryObj;

const pageStyles = html`
  <style>
    .tjtr {
      box-sizing: border-box;
      max-width: var(--tk-space-container);
      margin: 0 auto;
      padding: var(--tk-space-40) var(--tk-space-24) var(--tk-space-96);
      font-family: var(--tk-font-body);
      font-size: var(--tk-text-body-m-size);
      font-weight: var(--tk-text-body-m-weight);
      line-height: var(--tk-text-body-m-leading);
      color: var(--tk-color-text-primary);
      /* Canvas follows the theme's base surface (the 5.4 dark-sweep rule). */
      background: var(--tk-color-surface-base);
    }
    .tjtr h1 {
      margin: 0 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-3-size);
      font-weight: var(--tk-text-heading-3-weight);
      line-height: var(--tk-text-heading-3-leading);
    }
    .tjtr h2 {
      margin: var(--tk-space-40) 0 var(--tk-space-8);
      font-family: var(--tk-font-heading);
      font-size: var(--tk-text-heading-5-size);
      font-weight: var(--tk-text-heading-5-weight);
      line-height: var(--tk-text-heading-5-leading);
    }
    .tjtr p {
      margin: 0 0 var(--tk-space-12);
      max-width: var(--tk-space-container);
    }
    .tjtr .tjtr-note {
      color: var(--tk-color-text-secondary);
    }
    .tjtr ul {
      margin: 0 0 var(--tk-space-16);
      padding-left: var(--tk-space-24);
    }
    .tjtr li {
      margin: 0 0 var(--tk-space-8);
    }
    .tjtr table {
      box-sizing: border-box;
      width: 100%;
      margin: 0 0 var(--tk-space-16);
      border-collapse: collapse;
      font-size: var(--tk-text-body-s-size);
      line-height: var(--tk-text-body-s-leading);
      text-align: left;
    }
    .tjtr th,
    .tjtr td {
      padding: var(--tk-space-8) var(--tk-space-12) var(--tk-space-8) 0;
      border-bottom: 1px solid var(--tk-color-border-default);
      vertical-align: middle;
    }
    .tjtr th {
      font-size: var(--tk-text-body-xs-size);
      font-weight: var(--tk-text-body-s-bold-weight);
      letter-spacing: var(--tk-text-caps-s-tracking);
      text-transform: uppercase;
      color: var(--tk-color-text-secondary);
    }
    .tjtr code {
      /* Inline code renders the mono chain (story 11.2); block and inline
         alike. */
      font-family: var(--tk-font-mono);
      white-space: nowrap;
    }
    .tjtr .tjtr-swatch {
      box-sizing: border-box;
      display: inline-block;
      vertical-align: middle;
      width: var(--tk-space-40);
      height: var(--tk-space-24);
      border: 1px solid var(--tk-color-border-strong);
      border-radius: var(--tk-radius-xs);
    }
    /* chip-ink specimen: white ink ON the purple field — the only ground it
       is legal on (the 16.2/16.3 authored pair, theme-invariant). */
    .tjtr .tjtr-swatch--chip {
      display: inline-flex;
      align-items: center;
      justify-content: center;
      border: none;
      background: var(--tj-color-chip-fill);
      color: var(--tj-color-chip-ink);
      font-family: var(--tj-font-ui);
      font-size: var(--tj-text-cta-label-size);
      font-weight: var(--tj-text-cta-label-weight);
    }
    /* «инвариантно»/«нет поверхностей» is content — it takes the secondary
       step, never the restricted muted token. */
    .tjtr .tjtr-invariant {
      color: var(--tk-color-text-secondary);
    }
    .tjtr .tjtr-radius-box {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-64);
      height: var(--tk-space-64);
      border: 2px solid var(--tj-color-divider-strong);
    }
    .tjtr .tjtr-space-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-text-body-s-size);
      background: var(--tj-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tjtr .tjtr-shadow-box {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-120);
      height: var(--tk-space-64);
      background: var(--tj-color-card);
      border-radius: var(--tj-radius-card);
    }
    .tjtr .tjtr-duration-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-text-body-s-size);
      background: var(--tj-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tjtr .tjtr-curve {
      box-sizing: border-box;
      display: inline-block;
      width: var(--tk-space-96);
      height: var(--tk-space-96);
    }
    .tjtr .tjtr-z-bar {
      box-sizing: border-box;
      display: inline-block;
      height: var(--tk-space-12);
      background: var(--tj-color-focus-ring);
      border-radius: var(--tk-radius-xs);
      vertical-align: middle;
    }
    .tjtr .tjtr-specimen {
      margin: 0;
      overflow-wrap: anywhere;
      color: var(--tj-color-ink-100);
    }
  </style>
`;

/* --- Derivation helpers: STRUCTURE only — every VALUE comes from the maps --- */

/** The dark-layer override of a token, or null when it is theme-invariant. */
function darkValueOf(name: string): string | null {
  return Object.prototype.hasOwnProperty.call(darkColorTokens, name)
    ? darkColorTokens[name as keyof typeof darkColorTokens]
    : null;
}

/**
 * Tokens that may NOT paint a live specimen: invariant (no dark override)
 * AND outside the sweep-legal purple/gold families. Structure — a name set,
 * never a value. chip-ink is listed separately (it renders on the purple
 * ground specimen above).
 */
const UNPAINTABLE_INVARIANTS: readonly string[] = [
  '--tj-color-ink-200',
  '--tj-color-ink-reference-time',
];

/** One table row for a color token: light/dark text values + live specimen. */
function colorRow([name, light]: [string, string]): TemplateResult {
  const dark = darkValueOf(name);
  const unpaintable = UNPAINTABLE_INVARIANTS.includes(name);
  return html`
    <tr>
      <td><code>${name}</code></td>
      <td><code>${light}</code></td>
      <td>
        ${dark
          ? html`<code>${dark}</code>`
          : html`<span class="tjtr-invariant">инвариантно</span>`}
      </td>
      <td>
        ${name === '--tj-color-chip-ink'
          ? html`<span class="tjtr-swatch tjtr-swatch--chip">Aa</span>`
          : unpaintable
            ? html`<span class="tjtr-invariant">нет поверхностей</span>`
            : html`<span class="tjtr-swatch" style="background: var(${name})"></span>`}
      </td>
    </tr>
  `;
}

const colorsTable = (rows: [string, string][]): TemplateResult => html`
  <table>
    <thead>
      <tr>
        <th>Токен</th>
        <th>Светлая тема</th>
        <th>Тёмная тема</th>
        <th>Живой образец</th>
      </tr>
    </thead>
    <tbody>
      ${rows.map(colorRow)}
    </tbody>
  </table>
`;

/* --- Motion: sample a css cubic-bezier into SVG polyline points --- */

/** Uniformly-x-sampled points of a cubic-bezier(…) string (structure, no values). */
function bezierSamples(spec: string): Array<[number, number]> {
  const m = /cubic-bezier\(([-\d.]+),([-\d.]+),([-\d.]+),([-\d.]+)\)/.exec(spec);
  if (!m) return [];
  const [x1, y1, x2, y2] = m.slice(1).map(Number);
  const bx = (t: number): number => 3 * (1 - t) ** 2 * t * x1 + 3 * (1 - t) * t ** 2 * x2 + t ** 3;
  const by = (t: number): number => 3 * (1 - t) ** 2 * t * y1 + 3 * (1 - t) * t ** 2 * y2 + t ** 3;
  const points: Array<[number, number]> = [];
  for (let i = 0; i <= 20; i += 1) {
    const x = i / 20;
    // x(t) is monotonic for these curves — bisect for the param at x.
    let lo = 0;
    let hi = 1;
    for (let k = 0; k < 32; k += 1) {
      const mid = (lo + hi) / 2;
      if (bx(mid) < x) lo = mid;
      else hi = mid;
    }
    const t = (lo + hi) / 2;
    points.push([x, by(t)]);
  }
  return points;
}

/** Static SVG preview of a curve token — no animation (baseline-deterministic). */
function curveSvg(spec: string): TemplateResult {
  // Overshoot curves (y outside 0..1) fit the padded box: [-0.3, 1.3] → 5..125.
  const px = (p: [number, number]): string =>
    `${(p[0] * 100).toFixed(1)},${(125 - ((p[1] + 0.3) / 1.6) * 120).toFixed(1)}`;
  const points = bezierSamples(spec).map(px).join(' ');
  return html`
    <svg
      class="tjtr-curve"
      viewBox="0 0 100 130"
      preserveAspectRatio="none"
      aria-hidden="true"
      focusable="false"
    >
      <line x1="0" y1="102.5" x2="100" y2="102.5" style="stroke: var(--tj-color-divider)" />
      <line x1="0" y1="27.5" x2="100" y2="27.5" style="stroke: var(--tj-color-divider)" />
      <polyline
        points="${points}"
        fill="none"
        style="stroke: var(--tj-color-link); stroke-width: 3"
      />
    </svg>
  `;
}

/* --- Stories ------------------------------------------------------------------ */

export const Colors: Story = {
  name: 'Цвета',
  render: () => {
    // The ТЖ table IS semantic — no scale/alias indirection to split by.
    const semantic = Object.entries(colorTokens as TokenMap);
    return html`
      ${pageStyles}
      <main class="tjtr">
        <h1>ТЖ — токены: цвета</h1>
        <p class="tjtr-note">
          Значения сгенерированы из дизайн-модели (<code>pnpm gen:tokens:tj</code>,
          источник — DESIGN.md) и приведены ровно в том виде, в котором их
          потребляют компоненты. ТЖ-таблица целиком семантическая — шкал и
          алиасов-посредников нет. Тёмная колонка — семантические
          переопределения слоя <code>data-tj-theme="dark"</code>; «инвариантно»
          значит, что тёмный слой токен не переопределяет.
        </p>
        <p class="tjtr-note">
          Колонка «Живой образец» рендерится самим токеном
          (<code>var(--tj-…)</code>): переключите контрол Theme — образцы
          перевернутся вместе со слоем. Инвариантные чернила
          <code>--tj-color-ink-200</code> (светлая CTA-заливка — флип несёт
          семантика <code>cta-fill</code>) и
          <code>--tj-color-ink-reference-time</code> (не закреплён в тёмной)
          поверхностей не красят; <code>--tj-color-chip-ink</code> показан
          чернилами на собственном фиолетовом поле — единственной поверхности,
          где пара легальна.
        </p>

        <h2>Семантические токены</h2>
        <p class="tjtr-note">
          Поверхности, разделители, чернила, ссылки, фиолетовые поля, CTA-пара
          и кольцо фокуса. Ограниченные чернила (reference-meta/time, engage)
          несут ограничения в колонке правил на странице «Регистры ТЖ».
        </p>
        ${colorsTable(semantic)}
      </main>
    `;
  },
};

export const Typography: Story = {
  name: 'Типографика',
  render: () => {
    // Group per-slot tokens (…-size/-weight/-leading) by stem, in emission
    // order — names only, values stay in the map.
    const slots: Array<{ stem: string; parts: Record<string, string> }> = [];
    for (const [name, value] of Object.entries(typographyTokens as TokenMap)) {
      if (!name.startsWith('--tj-text-')) continue;
      const rest = name.replace('--tj-text-', '');
      const part = rest.match(/-(size|weight|leading)$/)?.[1];
      if (!part) continue;
      const stem = rest.slice(0, rest.length - part.length - 1);
      const slot = slots.find((s) => s.stem === stem) ?? (slots.push({ stem, parts: {} }), slots.at(-1)!);
      slot.parts[part] = value;
    }
    const fonts = Object.entries(typographyTokens as TokenMap).filter(([n]) =>
      n.startsWith('--tj-font-'),
    );
    // The reading register is Charter — structure, a name set (probe10: the
    // lead/body/body-link slots are the serif species; all else is grotesque).
    const READING_STEMS: readonly string[] = ['article-lead', 'article-body', 'body-link'];
    const familyFor = (stem: string): string =>
      READING_STEMS.includes(stem) ? 'var(--tj-font-reading)' : 'var(--tj-font-ui)';
    return html`
      ${pageStyles}
      <main class="tjtr">
        <h1>ТЖ — токены: типографика</h1>
        <p class="tjtr-note">
          Типографика инвариантна по темам: один набор на обе. Каждая строка —
          слот с его размером, насыщенностью и межстрочным; образец справа
          рендерится живыми токенами. Семей всего две (FR-20): гротеск
          <code>ui</code> — интерфейс и все заголовки, серифный
          <code>reading</code> — колонка чтения статьи.
        </p>

        <h2>Слоты текста</h2>
        <table>
          <thead>
            <tr>
              <th>Слот</th>
              <th>Размер</th>
              <th>Насыщенность</th>
              <th>Межстрочный</th>
              <th>Образец</th>
            </tr>
          </thead>
          <tbody>
            ${slots.map(
              ({ stem, parts }) => html`
                <tr>
                  <td><code>${stem}</code></td>
                  <td><code>${parts.size ?? '—'}</code></td>
                  <td><code>${parts.weight ?? '—'}</code></td>
                  <td><code>${parts.leading ?? '—'}</code></td>
                  <td
                    style="font-family: ${familyFor(stem)}; font-size: var(--tj-text-${stem}-size); font-weight: var(--tj-text-${stem}-weight); ${parts.leading
                      ? `line-height: var(--tj-text-${stem}-leading);`
                      : ''}"
                  >
                    <p class="tjtr-specimen">Как читается город</p>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Слоты семейств</h2>
        <p class="tjtr-note">
          Стек начинается с лицензируемых семейств референса (Graphik,
          Charter) и несёт открытые cyrillic-способные fallback (Inter /
          PT Serif — политика OQ-8: байтов шрифтов в ките нет). Переопределение
          слота заменяет значение целиком — повторите fallback в конце.
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Стек</th><th>Тёмная тема</th></tr>
          </thead>
          <tbody>
            ${fonts.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td><span class="tjtr-invariant">инвариантно</span></td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </main>
    `;
  },
};

export const Surfaces: Story = {
  name: 'Форма и поверхность',
  render: () => {
    const radii = Object.entries(radiusTokens as TokenMap);
    const scale = Object.entries(spaceTokens as TokenMap).filter(
      ([n]) => /^--tj-space-\d+$/.test(n),
    );
    const layout = Object.entries(spaceTokens as TokenMap).filter(
      ([n]) => !/^--tj-space-\d+$/.test(n),
    );
    const shadows = Object.entries(shadowTokens as TokenMap);
    // Derived from the maps — bars can never overflow if the scale grows.
    const spaceScaleMax = Math.max(
      ...scale.map(([, v]) => parseFloat(v) || 0),
      1,
    );
    return html`
      ${pageStyles}
      <main class="tjtr">
        <h1>ТЖ — токены: форма и поверхность</h1>
        <p class="tjtr-note">
          Радиусы, отступы и макетные константы инвариантны по темам. ТЖ —
          FLAT-язык: единственная тень — <code>overlay</code> (панель
          поисковых подсказок), и в тёмной теме она СОХРАНЯЕТСЯ как есть —
          иерархию строят тональные ступени поверхностей, а не элевация
          (правило прямо противоположно банковскому коллапсу теней).
        </p>

        <h2>Радиусы</h2>
        <p class="tjtr-note">
          Тихая геометрия: карточки 25, панели 30, CTA 5 — не пилюли.
          Образцы рендерятся живыми токенами.
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Образец</th></tr>
          </thead>
          <tbody>
            ${radii.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tjtr-radius-box"
                      style="border-radius: var(${name})"
                    ></span>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Отступы</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Шкала</th></tr>
          </thead>
          <tbody>
            ${scale.map(([name, value]) => {
              const px = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tjtr-space-bar"
                      style="width: ${(100 * px) / spaceScaleMax}%"
                    ></span>
                  </td>
                </tr>
              `;
            })}
            ${layout.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td><span class="tjtr-invariant">макетная константа</span></td>
                </tr>
              `,
            )}
          </tbody>
        </table>
        <p class="tjtr-note">
          Макетные константы — оси самого ТЖ: колонка чтения 764/760, рельс
          290, главная колонка ~770, высота шапки 72, контейнер 1200. Ритм
          статьи — BYO: колонка чтения и есть единица измерения.
        </p>

        <h2>Тени</h2>
        <p class="tjtr-note">
          Единственная тень семейства; переключите контрол Theme — в тёмной
          теме образец сохранит её (инвариант по данным пробы, 17.2
          перепроверен свипом).
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Образец</th></tr>
          </thead>
          <tbody>
            ${shadows.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span class="tjtr-shadow-box" style="box-shadow: var(${name})"></span>
                  </td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </main>
    `;
  },
};

export const Motion: Story = {
  name: 'Моушен и z-шкала',
  render: () => {
    const curves = Object.entries(motionTokens as TokenMap).filter(([n]) =>
      n.includes('-curve-'),
    );
    const durations = Object.entries(motionTokens as TokenMap).filter(([n]) =>
      n.includes('-duration-'),
    );
    // Derived from the maps — bars can never overflow if the scale grows.
    const durationMax = Math.max(
      ...durations.map(([, v]) => parseFloat(v) || 0),
      1,
    );
    const zs = Object.entries(zTokens as TokenMap);
    const zMax = Math.max(...zs.map(([, v]) => parseFloat(v) || 0), 1);
    return html`
      ${pageStyles}
      <main class="tjtr">
        <h1>ТЖ — токены: моушен и z-шкала</h1>
        <p class="tjtr-note">
          Кривые и длительности — единственный источник движения семейства
          (AD-9); под <code>prefers-reduced-motion</code> длительности
          схлопываются в 0ms самим токеновым слоем. z-шкала — механика
          скаффолда (AD-12): два уровня у честного размера ростера, слот 200
          свободен под будущий шаг. Инвариантны по темам.
        </p>

        <h2>Кривые</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Профиль</th></tr>
          </thead>
          <tbody>
            ${curves.map(
              ([name, value]) => html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>${curveSvg(value)}</td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Длительности</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Шкала</th></tr>
          </thead>
          <tbody>
            ${durations.map(([name, value]) => {
              const ms = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span
                      class="tjtr-duration-bar"
                      style="width: ${(100 * ms) / durationMax}%"
                    ></span>
                  </td>
                </tr>
              `;
            })}
          </tbody>
        </table>

        <h2>Z-шкала</h2>
        <table>
          <thead>
            <tr><th>Токен</th><th>Значение</th><th>Уровень</th></tr>
          </thead>
          <tbody>
            ${zs.map(([name, value]) => {
              const level = Number.parseFloat(value);
              return html`
                <tr>
                  <td><code>${name}</code></td>
                  <td><code>${value}</code></td>
                  <td>
                    <span class="tjtr-z-bar" style="width: ${(100 * level) / zMax}%"></span>
                  </td>
                </tr>
              `;
            })}
          </tbody>
        </table>
      </main>
    `;
  },
};

/* --- Registers (spec 17.3) — rendered from the committed TOKENS.md ------ */

/** Render a markdown cell's `code` spans as <code> and **bold** as <strong>
 * (the TOKENS.md notes carry both; code wins — bold markers inside a code
 * span are code characters, not markup). */
function mdInline(cell: string): TemplateResult {
  const renderText = (text: string): TemplateResult =>
    html`${text
      .split('**')
      .map((part, index) => (index % 2 === 1 ? html`<strong>${part}</strong>` : part))}`;
  const parts = cell.split('`');
  return html`${parts.map((part, index) => (index % 2 === 1 ? html`<code>${part}</code>` : renderText(part)))}`;
}

export const Registers: Story = {
  name: 'Регистры ТЖ',
  render: () => {
    // Throws loudly when the generator's shape drifts (fail, never blank).
    const { fontSlots, fontSlotsNote, darkLayer, darkLayerNote, invariants, radiusNote, notes } =
      tjRegistersData(tokensMarkdown);
    return html`
      ${pageStyles}
      <main class="tjtr">
        <h1>ТЖ — регистры</h1>
        <p class="tjtr-note">
          Реестры ТЖ сгенерированы в TOKENS.md (<code>pnpm gen:tokens:tj</code>)
          и процитированы дословно: тёмный слой со своими источниками,
          инварианты темы, семейные слоты шрифтов и AA-правила ограниченных
          чернил. Значения тёмного слоя показаны ТЕКСТОМ — живые образцы
          красок на странице «Цвета».
        </p>

        <h2>Тёмный слой (Story 15.2)</h2>
        <p class="tjtr-note">${mdInline(darkLayerNote)}</p>
        <table>
          <thead>
            <tr>
              <th>Токен</th>
              <th>Светлая</th>
              <th>Тёмная</th>
              <th>Источник</th>
              <th>Примечание</th>
            </tr>
          </thead>
          <tbody>
            ${darkLayer.rows.map(
              (row) => html`
                <tr>
                  <td><code>${row[0]}</code></td>
                  <td><code>${row[1]}</code></td>
                  <td><code>${row[2]}</code></td>
                  <td><code>${row[3]}</code></td>
                  <td>${row[4] ? mdInline(row[4]) : '—'}</td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Инварианты темы</h2>
        <p class="tjtr-note">
          Эти семантики сохраняют светлые значения в тёмной — переопределения
          не эмитируется (формулировки дословно из TOKENS.md):
        </p>
        <ul>
          ${invariants.map(
            ([token, rationale]) => html`
              <li><code>${token}</code> — ${mdInline(rationale)}</li>
            `,
          )}
        </ul>

        <h2>Семейные слоты (FR-20)</h2>
        <p class="tjtr-note">${mdInline(fontSlotsNote)}</p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Стек</th></tr>
          </thead>
          <tbody>
            ${fontSlots.rows.map(
              (row) => html`
                <tr>
                  <td><code>${row[0]}</code></td>
                  <td><code>${row[1]}</code></td>
                </tr>
              `,
            )}
          </tbody>
        </table>

        <h2>Регистры скруглений</h2>
        <p class="tjtr-note"> ${mdInline(radiusNote)} </p>

        <h2>AA-решения и ограничения</h2>
        <p class="tjtr-note">
          Правила ограниченных чернил и AA-оверрайдов процитированы из
          TOKENS.md дословно; механическая проверка пар живёт в тестах кита
          (<code>tests/tj-contrast.test.ts</code>), тёмный свип —
          <code>tests/visual/tj-dark-sweep.spec.ts</code>.
        </p>
        <table>
          <thead>
            <tr><th>Токен</th><th>Правило (TOKENS.md)</th></tr>
          </thead>
          <tbody>
            ${TJ_REQUIRED_NOTES.map(
              (token) => html`
                <tr>
                  <td><code>${token}</code></td>
                  <td>${mdInline(notes[token] ?? '')}</td>
                </tr>
              `,
            )}
          </tbody>
        </table>
      </main>
    `;
  },
};
