import { html, type TemplateResult } from 'lit';

import cem from '../custom-elements.json';

/**
 * Generated API reference for ТЖ component stories (spec 17.3) — the
 * src/api-reference.ts mold of the bank family, mirrored: the tables render
 * from the COMMITTED ТЖ CEM MANIFEST (custom-elements.json, regenerated by
 * `pnpm gen`, drift-gated by check:gen) — the docs cannot disagree with the
 * component layer. Autodocs/ArgsTable stays rejected for the same recorded
 * reason as the bank's (it would fork the API description surface and is not
 * baselined by the visual harness).
 *
 * Manifest descriptions are quoted VERBATIM (English jsdoc — the same source
 * that feeds the React wrapper generation); the page chrome around them is
 * Russian (OQ-4). Translating here would fork the single source.
 *
 * RECORDED ADJUSTMENT vs the bank mold — the theming-channel section states
 * the truth of the roster (17.3): the `--tj-<component>-<slot>` grammar is
 * RESERVED in CONVENTIONS.md, but the 16.1–16.5 roster declares ZERO
 * channels (each css.ts consumes semantic tokens directly). The section
 * documents the grammar and says exactly that — no invented rows.
 *
 * Styling consumes var(--tj-*) tokens ONLY (FR-17 family boundary: zero
 * --tk-* reads inside this package). Code spans render `monospace` — the
 * family's own code idiom (tj-cta/tj-news-card stories); the
 * --tk-font-mono chain belongs to the bank docs chrome and must not cross
 * the boundary.
 */

/** Minimal CEM shapes the renderer reads (schema 1.0.0 — see cem.config.mjs). */
interface CemType {
  text?: string;
}

interface CemAttribute {
  name: string;
  fieldName?: string;
  type?: CemType;
  default?: string;
  description?: string;
}

interface CemMember {
  kind?: string;
  name?: string;
  privacy?: string;
  static?: boolean;
  type?: CemType;
  description?: string;
}

interface CemEvent {
  name: string;
  type?: CemType;
  description?: string;
}

interface CemSlot {
  name?: string;
  description?: string;
}

interface CemDeclaration {
  tagName?: string;
  attributes?: CemAttribute[];
  members?: CemMember[];
  events?: CemEvent[];
  slots?: CemSlot[];
}

interface CemManifest {
  modules?: { declarations?: CemDeclaration[] }[];
}

const manifest = cem as CemManifest;

const REPO_URL = 'https://github.com/salacoste/tinkoff-ui-kit';
const CONVENTIONS_URL = `${REPO_URL}/blob/main/packages/tj-components/CONVENTIONS.md`;

/** Find the declaration for a tag name — missing tag fails LOUDLY (spec edge-case row). */
function findDeclaration(tag: string): CemDeclaration {
  for (const module of manifest.modules ?? []) {
    const found = (module.declarations ?? []).find((d) => d.tagName === tag);
    if (found) return found;
  }
  throw new Error(
    `api-reference: tag ${tag} not found in custom-elements.json — run pnpm gen (the manifest is the API source of record).`,
  );
}

/** A short slot label: the default slot renders as «(по умолчанию)». */
const slotLabel = (name?: string): string => (name ? name : '(по умолчанию)');

const apiStyles = html`
  <style>
    .tjap {
      box-sizing: border-box;
      max-width: var(--tj-space-container);
      min-height: 100vh;
      margin: 0 auto;
      padding: var(--tj-space-40) var(--tj-space-24) var(--tj-space-64);
      font-family: var(--tj-font-ui);
      font-size: var(--tj-text-article-body-size);
      font-weight: var(--tj-text-article-body-weight);
      line-height: var(--tj-text-article-body-leading);
      color: var(--tj-color-ink-100);
      /* Canvas follows the theme's page surface (the dark-sweep canvas rule). */
      background: var(--tj-color-page);
    }
    .tjap h1 {
      margin: 0 0 var(--tj-space-8);
      font-size: var(--tj-text-article-h2-size);
      font-weight: var(--tj-text-article-h2-weight);
      line-height: var(--tj-text-article-h2-leading);
    }
    .tjap h2 {
      margin: var(--tj-space-32) 0 var(--tj-space-12);
      font-size: var(--tj-text-cta-label-size);
      font-weight: var(--tj-text-article-h2-weight);
      line-height: var(--tj-text-cta-label-leading);
    }
    .tjap p {
      max-width: var(--tj-space-column-reading-body);
      margin: 0 0 var(--tj-space-12);
    }
    .tjap .tjap-note {
      /* Notes are CARD surfaces: ink-300 is the AA meta step on the card,
         not on the bare page (the 15.2 contract). */
      padding: var(--tj-space-12) var(--tj-space-16);
      font-size: var(--tj-text-time-meta-size);
      font-weight: var(--tj-text-time-meta-weight);
      line-height: var(--tj-text-byline-leading);
      color: var(--tj-color-ink-300);
      background: var(--tj-color-card);
      border-radius: var(--tj-radius-card);
    }
    .tjap table {
      box-sizing: border-box;
      width: 100%;
      margin: 0 0 var(--tj-space-16);
      border-collapse: collapse;
      text-align: left;
      /* Tables are CARD surfaces (the 15.2 ink-300-on-card law): the header
         step ink-300 is AA on the card, 4.478 on the bare page — the same
         reason the suite canvases card their notes. */
      background: var(--tj-color-card);
      padding: var(--tj-space-8) var(--tj-space-16);
      border-radius: var(--tj-radius-card);
    }
    .tjap th,
    .tjap td {
      padding: var(--tj-space-8) var(--tj-space-12) var(--tj-space-8) 0;
      border-bottom: 1px solid var(--tj-color-divider);
      vertical-align: top;
    }
    .tjap th {
      font-size: var(--tj-text-time-meta-size);
      font-weight: var(--tj-text-byline-weight);
      color: var(--tj-color-ink-300);
    }
    .tjap code {
      /* The family's code idiom — monospace (OQ-8: no bundled font faces;
         --tk-font-mono must not cross the FR-17 boundary). */
      font-family: monospace;
      font-size: var(--tj-text-cta-label-size);
      color: var(--tj-color-ink-100);
    }
    .tjap td code {
      white-space: nowrap;
    }
    .tjap .tjap-foot {
      max-width: var(--tj-space-column-reading-body);
      margin: var(--tj-space-32) 0 0;
      padding: var(--tj-space-12) var(--tj-space-16);
      font-size: var(--tj-text-time-meta-size);
      font-weight: var(--tj-text-time-meta-weight);
      line-height: var(--tj-text-byline-leading);
      color: var(--tj-color-ink-300);
      background: var(--tj-color-card);
      border-left: var(--tj-space-4) solid var(--tj-color-divider-strong);
      border-radius: var(--tj-radius-input);
    }
    .tjap .tjap-foot a {
      color: var(--tj-color-link);
    }
  </style>
`;

/**
 * The generated API page for one ТЖ element: attributes + property-only
 * channels, events, slots — straight from the manifest — plus the
 * CONVENTIONS.md contract link every component page carries.
 */
export function apiReferenceDoc(tag: string): TemplateResult {
  const declaration = findDeclaration(tag);
  const attributes = declaration.attributes ?? [];
  const events = declaration.events ?? [];
  const slots = declaration.slots ?? [];

  // Property-only channels: public INSTANCE fields with no reflected attribute.
  // Derived from members by ABSENCE of an attribute fieldName — never a hand
  // list. Static union constants are class API, not element props — excluded.
  const attributeFields = new Set(attributes.map((a) => a.fieldName ?? a.name));
  const propertyOnly = (declaration.members ?? []).filter(
    (m) =>
      m.kind === 'field' && !m.privacy && !m.static && m.name && !attributeFields.has(m.name),
  );

  return html`
    ${apiStyles}
    <main class="tjap" lang="ru">
      <h1>API — ${tag}</h1>
      <p class="tjap-note">
        Таблица сгенерирована из манифеста компонентов
        (<code>custom-elements.json</code>, обновляется командой
        <code>pnpm gen</code>) — значения не могут разойтись с кодом.
        Описания процитированы из jsdoc-документации компонента на английском:
        манифест — единый источник, он же питает генерацию React-обёрток.
      </p>

      <h2>Атрибуты и свойства</h2>
      <table>
        <thead>
          <tr>
            <th>Атрибут</th>
            <th>Свойство</th>
            <th>Тип</th>
            <th>По умолчанию</th>
            <th>Описание</th>
          </tr>
        </thead>
        <tbody>
          ${attributes.map(
            (a) => html`
              <tr>
                <td><code>${a.name}</code></td>
                <td><code>${a.fieldName ?? a.name}</code></td>
                <td><code>${a.type?.text ?? '—'}</code></td>
                <td>${a.default ? html`<code>${a.default}</code>` : '—'}</td>
                <td>${a.description ?? '—'}</td>
              </tr>
            `,
          )}
          ${propertyOnly.map(
            (m) => html`
              <tr>
                <td>—</td>
                <td><code>${m.name}</code></td>
                <td><code>${m.type?.text ?? '—'}</code></td>
                <td>—</td>
                <td>
                  ${m.description ?? '—'}
                  <br />
                  <em>Только свойство: не отражается атрибутом.</em>
                </td>
              </tr>
            `,
          )}
        </tbody>
      </table>

      <h2>События</h2>
      ${events.length
        ? html`
            <table>
              <thead>
                <tr><th>Событие</th><th>Тип</th><th>Описание</th></tr>
              </thead>
              <tbody>
                ${events.map(
                  (e) => html`
                    <tr>
                      <td><code>${e.name}</code></td>
                      <td><code>${e.type?.text ?? 'CustomEvent'}</code></td>
                      <td>${e.description ?? '—'}</td>
                    </tr>
                  `,
                )}
              </tbody>
            </table>
          `
        : html`<p>Кастомных событий нет — см. описание компонента.</p>`}

      <h2>Слоты</h2>
      ${slots.length
        ? html`
            <table>
              <thead>
                <tr><th>Слот</th><th>Описание</th></tr>
              </thead>
              <tbody>
                ${slots.map(
                  (s) => html`
                    <tr>
                      <td><code>${slotLabel(s.name)}</code></td>
                      <td>${s.description ?? '—'}</td>
                    </tr>
                  `,
                )}
              </tbody>
            </table>
          `
        : html`<p>Слотов нет — контент задаётся атрибутами и свойствами.</p>`}

      <h2>Каналы темизации</h2>
      <p>
        Грамматика каналов <code>--tj-${tag.replace(/^tj-/, '')}-&lt;slot&gt;</code>
        зарезервирована в CONVENTIONS.md, но ростер 16.1–16.5 пока не объявил
        ни одного канала: стилевые модули потребляют семантические токены
        <code>--tj-*</code> напрямую (проверяемый факт — тест потреблённых
        токенов выводит пространство имён хуков из реальных директорий).
        Настройка — на уровне семантик; появившийся канал будет перечислен в
        jsdoc стилевого модуля
        (<code>${tag.replace(/^tj-/, '')}.css.ts</code> в директории
        компонента).
      </p>

      <p class="tjap-foot">
        Контракт семейства — пропсы, события, controlled/uncontrolled-режимы,
        слоты и грамматика темизации — описан в
        <a href="${CONVENTIONS_URL}" target="_blank" rel="noreferrer noopener"
          >CONVENTIONS.md</a
        >
        репозитория.
      </p>
    </main>
  `;
}
