/**
 * pillkit-tj-tokens — design token package for the ТЖ sub-kit (story 15.2,
 * generated; the bank 1.1 mold, second instance).
 *
 * Programmatic access to the token system: typed name/value maps generated from
 * the ТЖ DESIGN.md (`./tokens.js`). Styles ship as the
 * `pillkit-tj-tokens/tokens.css` export: the side-effect import below pulls the
 * light `--tj-*` layer through bundlers that consume this source, while the
 * built library extracts the CSS to dist/index.css and strips the import from
 * dist JS — stylesheet consumers always use the export.
 *
 * Generated by `pnpm gen:tokens:tj` (scripts/generate.mjs — the shared root
 * core with the ТЖ config); DESIGN.md is the sole source of truth — never
 * hand-edit `tokens.css`, `tokens.ts`, or `TOKENS.md`. The dark layer (story
 * 15.2) re-declares the semantic color overrides on
 * `[data-tj-theme="dark"]` AND natively under `prefers-color-scheme: dark`
 * unless `data-tj-theme="light"` forces light — set the attribute on <html> to
 * override the OS preference either way.
 */
import './tokens.css';

export * from './tokens.js';
